export const technologies = ['TypeScript', 'Vue源码解读']

export const GithubPros = [
  'gitPractice',
  'ssrD-demo ',
  'webpac5 ',
  'vue3admin',
  'typescript-vue-tutorial',
  'minipack ',
  'reactLearning',
  'VUE2 ',
  'react-admin-master',
  'hello-github-actions',
  'BLOG',
  'HomePage',
  'projectdemo',
  'plan',
  'runpage',
  'node-api-cn',
  'wx_miniProgram',
  'vue-webpack',
  'productdata',
  'cartvue',
  'Person',
  'vuex-demo',
  'animate.css',
  'OPPO2',
  'angular-rk9uiw-heroes',
  'angular-ufg7wz-aeqggx_shopping'
]
